"""add avatar_filename and cover_filename to User

Revision ID: 3c9c96a48d53
Revises: 9c6e08f854be
Create Date: 2026-02-04 01:47:12.821282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9c96a48d53'
down_revision = '9c6e08f854be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_filename', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('cover_filename', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cover_filename')
        batch_op.drop_column('avatar_filename')

    # ### end Alembic commands ###
