"""add artwork and artwork_type tables

Revision ID: 7e85a34020f7
Revises: 63e1d10c0e4e
Create Date: 2026-02-02 16:46:37.913086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e85a34020f7'
down_revision = '63e1d10c0e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artwork_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('allowed_extensions', sa.String(length=256), nullable=True),
    sa.Column('max_file_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('artwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artwork_type_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('desc', sa.String(length=1024), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_type_id'], ['artwork_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artwork_artwork_type_id'), ['artwork_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artwork_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_artwork_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artwork_user_id'))
        batch_op.drop_index(batch_op.f('ix_artwork_timestamp'))
        batch_op.drop_index(batch_op.f('ix_artwork_artwork_type_id'))

    op.drop_table('artwork')
    op.drop_table('artwork_type')
    # ### end Alembic commands ###
